{{- $files := .Files.Glob "rules/*.yaml" }}
{{ if ($files) }}
{{- range $path, $fileContents := $files }}
{{- $groupName := regexReplaceAll "(^.*/)(.*)\\.yaml$" $path "${2}" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $groupName }}
  labels:
    {{- include "prometheusrule.labels" $ | nindent 4 }}
spec:
  groups:
    {{ $.Files.Get $path | nindent 4 }}
{{ end }}
{{ end }}
