name: Prometheus Rule Validations

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  promtool:
    name: check prometheus config files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peimanja/promtool-github-actions@master
        name: check prometheus rules
        with:
          promtool_actions_subcommand: 'rules'
          promtool_actions_files: '*/rules/*.yaml'
          promtool_actions_version: '2.14.0'
          promtool_actions_comment: false


